export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const CREATE_PDP = 'CREATE_PDP';
export const CREATE_PDP_SECTION = 'CREATE_PDP_SECTION';
export const CREATE_PDP_QUESTION = 'CREATE_PDP_QUESTION';
export const CREATE_PDP_ANSWER = 'CREATE_PDP_ANSWER';
